services:
  mysql:
    image: mysql:8.0
    container_name: wigell-mc-rental-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wigell_mc_db
    ports:
      - "6606:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    name: wigell_mc_db_data